"""fix errors

Revision ID: 7a3f3060767f
Revises: 9466e8419c48
Create Date: 2025-03-26 09:33:55.419176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a3f3060767f'
down_revision: Union[str, None] = '9466e8419c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info', sa.Column('icon', sa.String(), nullable=True))
    op.add_column('info', sa.Column('link', sa.String(), nullable=True))
    op.alter_column('info', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('info', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('info', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('info', 'filepath',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_info_icon'), 'info', ['icon'], unique=False)
    op.create_index(op.f('ix_info_link'), 'info', ['link'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_info_link'), table_name='info')
    op.drop_index(op.f('ix_info_icon'), table_name='info')
    op.alter_column('info', 'filepath',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('info', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('info', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('info', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('info', 'link')
    op.drop_column('info', 'icon')
    # ### end Alembic commands ###
